.TH lxqt-config-appearance "1" "January 2025" "LXQt 2.1.0" "LXQt Appearance Settings"
.SH NAME
lxqt-config-appearance \- GUI appearance application of \fBLXQt\fR: The Lightweight
Qt Desktop Environment
.SH SYNOPSIS
.B lxqt-config-appearance
.br
.SH DESCRIPTION
With this application you can set and configure the Qt / LXQt GUI appearance. Options
include configuring widget style, color palette, application toolbar, icon theme,
LXQt theme, font, cursor, and optionally GTK 2/3 style.
.P
On Linux/Unix, the look of a GUI application depends on the toolkit it is based on.
For LXQt, the overall look of many apps relies on the Qt framework GUI. The
\fBlxqt-config-appearance\fR application provides all aspects of configuring the
appearance of the \fBLXQt\fR desktop.
.P
All the remaining major aspects of LXQt appearance rely on the active Qt widget
style because the \fBLXQt\fR DE is based on the Qt framework.
.P
.SH OPTIONS
-v, --version  Displays version information.
.br
-h, --help     Displays help on command line options.
.br
--help-all     Displays help, including generic Qt options.
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxqt/lxqt-config/issues
.SH "SEE ALSO"
\fBLXQt\fR it has been tailored for users who value simplicity, speed, and
an intuitive interface. LXQt is also intended for less powerful machines. Also,
See:
.P
\fBlxqt-session.1\fR  LXQt Session Manager
.P
\fBlxqt-config.1\fR  LXQt Configuration Center
