.TH lxqt-config-mouse "1" "September 2012" "LxQt\-qt\ 0.5.0" "LxQt\-qt\ Mouse settings"
.SH NAME
lxqt-config-mouse \- Application of \fBLxQt-qt\fR: the faster and lighter QT Desktop Environment
.SH SYNOPSIS
.B lxqt-config-mouse
.br
.SH DESCRIPTION
This its a simple GUI mouse theme configuraton (by the moment) for the LxQt-qt desktop environment.
Also can manage theme installation for it (localy for/per user only).
.P
\fBLxQt-qt\fR is an advanced, easy-to-use, and fast desktop environment based on Qt
technologies, ships several core desktop components, all of which are optional:
.P
 * Panel
 * Desktop
 * Application launcher
 * Settings center \fI(related to this)\fR
 * Session handler
 * Polkit handler
 * SSH password access
 * Display manager handler
.P
These components perform similar actions to those available in other desktop
environments, and their name is self-descriptive.  They are usually not launched
by hand but automatically, when choosing a \fBLxQt\-qt\fR session in the Display
Manager.
.P
.SH "REPORTING BUGS"
Report bugs to https://github.com/LxQt-qt/LxQt-qt/issues
.SH "SEE ALSO"
\fBLxQt-qt\fR it has been tailored for users who value simplicity, speed, and
an intuitive interface, also intended for less powerful machines. See also:
.\" any module must refers to session app, for more info on start it
.P
\fBlxqt-config.1\fR  LxQt-qt application for performing settings on many applications
.P
.SH AUTHOR
This manual page was created by \fBPICCORO Lenz McKAY\fR \fI<mckaygerhard@gmail.com>\fR
for \fBLxQt-qt\fR project and VENENUX GNU/Linux but can be used by others.
