.TH LXQT-CONFIG-INPUT "1" "January 2025" "LXQt 2.1.0" "LXQt Input Settings"
.SH NAME
lxqt-config-input \- Application of \fBLXQt\fR: The Lightweight Qt Desktop
Environment
.SH SYNOPSIS
.B lxqt-config-input
.br
.SH DESCRIPTION
This is a simple GUI application for keyboard, mouse, and touchpad settings.
(Currently it can only run under X11.)
.P
.SH OPTIONS
-s, --show-page <name>  Choose the page to be shown.
.br
--load-touchpad         Load last touchpad settings.
.br
-v, --version           Displays version information.
.br
-h, --help              Displays help on command line options.
.br
--help-all              Displays help, including generic Qt options
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxqt/lxqt-config/issues
.SH "SEE ALSO"
\fBLXQt\fR has been tailored for users who value simplicity, speed, and
an intuitive interface, also intended for less powerful machines. See also:
.\" any module must refers to session app, for more info on start it
.P
\fBlxqt-config(1)\fR  LXQt Configuration Center
