.TH lxqt-config-locale "17" "March 2015" "LXQt\ 0.9.0" "LXQt\ GUI settings"
.SH NAME
lxqt-config-locale \- GUI locale settings application of \fBLXQt\fR: the faster and lighter QT Desktop Environment
.SH SYNOPSIS
.B lxqt-config-locale
.br
.SH DESCRIPTION
With this application you can setting and configuring default language, digits format, and other regional customization.
.P
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxde/lxde-qt/issues
.SH "SEE ALSO"
\fBLXQt\fR it has been tailored for users who value simplicity, speed, and
an intuitive interface, also intended for less powerful machines. See also:
.\" any module must refers to session app, for more info on start it
.P
\fBlxqt-session.1\fR  LXQt module for manage LXQt complete environment.
.P
\fBlxqt-config.1\fR  LXQt application for general config and settings.
.P
\fBqtconfig-qt4.1\fR  Qt4 application for gui and appereance settings over all qt4 based software.
.P
.SH AUTHOR
This manual page was created by \fBPICCORO Lenz McKAY\fR \fI<mckaygerhard@gmail.com>\fR
for \fBLXQt\fR project and VENENUX GNU/Linux but can be used by others.
